# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201aad1ad8945d0fc4976111c76e40959e355c2f9b7493287efd29bd9b5a9d144383f0d56ca5cfac40b2b85dce055da79cccc0a2db4192d7b75521d6f1bd0289

test:
  secret_key_base: a5743c3491f4ce4835eebf8b628bd73c48e4ddb3145542be28c64f813cce216ad83270b2e02b462c866a9a299cfb73d2d8d3d66b17dafd3403850548a9d03d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
